---
- hosts: all
  become: yes
  tasks:
          - name: install apache2
            apt:
                    name: apache2
                    state: absent 
                    

          - name: install tree
            apt:
                    name: tree
                    state: present