---
- hosts: mywebserver
  become: yes
  tasks:
      - name: i want to install Openjdk8 on ubuntu node
        apt:
            name: "{{myopenjdk8forubuntu}}"
            state: present
        when: ansible_os_family == "Debian"

      - name: i want to install Openjdk8 on RedHat node
        yum:
            name: "{{myopenjdk8forredhat}}"
            state: present
        when: ansible_os_family == "RedHat"