---
- hosts: all
  become: yes
  tasks:
      - name: i want to install Openjdk8 on ubuntu
        apt:
            name: openjdk-8-jre
            state: present
        when: ansible_os_family == "Debian"