---
- hosts: all
  become: yes
  tasks:
     - include_tasks: myfilehandle.yaml

     - name: i want to install apache2 on ubuntu
       apt: 
         name: apache2
         state: present
       when: ansible_os_family== "Debian"
      
     - name: i want to install httpd on redhat
       apt: 
         name: httpd
         state: present
       when: ansible_os_family== "RedHat"

     - name: i want to replace apache2 with my template
       template:
          src: apache2.j2
          dest: /var/www/html/index.html