---
- hosts: 172.31.33.252
  become: yes
  tasks: 
      - name: i want to install apache2 on ubuntu
        apt:
          name: apache2
          state: present
        
      
      - name: i want to replace apache2 template with my jinja template
        template:
           src: myindex.j2
           dest: /var/www/html/index.html
        notify: restartwebserver

  