---
- hosts: 172.31.4.249
  become: yes
  tasks:
          - name: install nginx
            apt:
                    name: nginx
                    state: present


---
- hosts: 172.31.9.14
  become: yes
  tasks:
          - name: install apache
            apt:
                    name: apache
                    state: present